# Generated by Django 5.1.2 on 2024-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_description_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, height_field='260', null=True, upload_to='products', verbose_name='Image', width_field='260'),
        ),
    ]
