# Generated by Django 5.1.2 on 2024-10-24 13:15

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products', verbose_name='Image'),
        ),
    ]
