# Generated by Django 5.1.2 on 2024-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_usercart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
