# Generated by Django 5.1.2 on 2024-10-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_usercart_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
