# Generated by Django 5.1.2 on 2024-10-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_usercart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
