# Generated by Django 5.1.2 on 2024-11-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_name_en_category_name_ka'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ka',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ka',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
